### ISSUE TITLE
Independent publishing on Lerna 3.x fails

### ISSUE THREAD

**Issue by Fionoble** [Shopify/shipit-engine#1089]
When trying to release independently versioned package on lerna 3.x it fails on this line: https://github.com/Shopify/shipit-engine/blob/master/lib/snippets/publish-lerna-independent-packages#L4

It seems like the folder structures have changed in lerna 3.

Error output:
<details>
```
$ publish-lerna-independent-packages
pid: 30896
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '/app/data/stacks/shopify/app-extension-libs/production/deploys/1015968/node_modules/lerna/lib/Repository'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/artifacts/ruby/2.6.0/bundler/gems/shipit-engine-c4886a9b87f4/lib/snippets/publish-lerna-independent-packages:4:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
publish-lerna-independent-packages terminated with exit status 1
```
</details>

**Comment by Fionoble** [comment]
Fixed by: https://github.com/Shopify/shipit-engine/pull/1165
