### ISSUE TITLE
How to setup local development and run unit-tests?

### ISSUE THREAD

**Issue by eldadvcita** [Shopify/shipit-engine#1124]
Hi,
I'm interested in customizing Shipit. To do so, I need to set up a local development environment.
So far, I was able to run Shipit locally using MySQL and pack it using a Dockerfile (ruby:2.6.4) & docker-compose.

When I try to run the test suite, I get the following exception:
```
bundle exec rake db:create db:schema:load test --trace
** Invoke load_app (first_time)
** Execute load_app
[DEPRECATED] `Bundler.clean_env` has been deprecated in favor of `Bundler.unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.original_env` (called at /usr/src/shipit-engine/lib/shipit/command.rb:16)
** Invoke db:create (first_time)
** Invoke load_app 
** Invoke app:db:create (first_time)
** Invoke app:db:load_config (first_time)
** Invoke app:environment (first_time)
** Execute app:environment
** Execute app:db:load_config
** Execute app:db:create
Configure a supported :charset and ensure innodb_large_prefix is enabled to support indexes on varchar(255) string columns.
Couldn't create 'db/test.sqlite3' database. Please check your configuration.
rake aborted!
Configure a supported :charset and ensure innodb_large_prefix is enabled to support indexes on varchar(255) string columns.
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:260:in `create_database'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/mysql_database_tasks.rb:16:in `create'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <top (required)>'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/ruby/2.6.0/bin/rake:23:in `load'
/usr/local/bundle/ruby/2.6.0/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => db:create => app:db:create
```

I tried to run the task with a different env without success, for example:
```
ENVIRONMENT=test RACK_ENV=test RAILS_ENV=test bundle exec rake db:create db:schema:load test --trace
# It results in the same error as above
```

**Q:** How should I run unit-tests?

**Comment by casperisfine** [comment]
Your Mysql is too old or misconfigured.

You should read up on `ensure innodb_large_prefix is enabled to support indexes on varchar(255) string columns.`.

You can also just use `sqlite3` in development for now.

**Comment by eldadvcita** [comment]
Hi @casperisfine ,
Thank you for the reqply. Which version of MySQL should I use?

**Comment by casperisfine** [comment]
IIRC it should work out of the box with `>= 5.7.8`, but I'm not certain hence why I suggested you google the error message.

**Comment by eldadvcita** [comment]
Again, thank you for your reply!
I understand the meaning of the error, what I don't understand is why Shipit checks if MySQL is configured properly as I explicitly specified `sqlite3` as the adapter. That's the default.

**Comment by casperisfine** [comment]
> I don't understand is why Shipit checks if MySQL is configured properly as I explicitly specified `sqlite3` as the adapter.

Based on the output you pasted, no. You specified `mysql2` adapter with a database named `db/test.sqlite3`.

**Comment by eldadvcita** [comment]
I just upgraded the DB from 5.6 to 5.7.8 as you advised. When I try to create the DB I get the following error:
```
$ bundle exec rake db:create db:migrate

shipit_1                 | Database 'shipit_dev' already exists
shipit_1                 | Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`sqlite3` DEFAULT CHARACTER SET `utf8`' at line 1
shipit_1                 | Couldn't create 'db/test.sqlite3' database. Please check your configuration.
shipit_1                 | rake aborted!
shipit_1                 | ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`sqlite3` DEFAULT CHARACTER SET `utf8`' at line 1
shipit_1                 | /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
shipit_1                 | /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
shipit_1                 | /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
shipit_1                 | /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:201:in `block (2 levels) in execute'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:200:in `block in execute'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
shipit_1                 | /usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:199:in `execute'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/mysql/database_statements.rb:41:in `execute'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:256:in `create_database'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/mysql_database_tasks.rb:16:in `create'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:126:in `create'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:476:in `each'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:475:in `each'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
shipit_1                 | /usr/local/bundle/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
shipit_1                 | /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
shipit_1                 | /usr/local/bundle/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
shipit_1                 | /usr/local/bundle/bin/bundle:23:in `load'
shipit_1                 | /usr/local/bundle/bin/bundle:23:in `<main>'
```

**shipit-engine database.yaml**
```
default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3
```

**GitHub app database.yaml**
```
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL') {'mysql2://root:123456@127.0.0.1:3306'} %>

development:
  <<: *default
  database: shipit_dev

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  database: shipit_production
```

**Comment by casperisfine** [comment]
I don't want to be blunt or anything, but you are asking basic Rails development questions. That is not what this bug tracker is for.

So ` '.`sqlite3` DEFAULT CHARACTER SET `utf8`' at line 1` is because as I said previously you are using `mysql2` with a database name of `something.sqlite3`, which is invalid as database names can't container `.`. It also clearly indicates your database.yml is very likely misconfigured.

> GitHub app database.yaml

I'd need to dig deeper, but pretty sure Rails is merging the option from the `url:` field with the other ones you specify explictly, hence how you end up with a frankenstein configuration.

So I'd advise you to learn Rails basics first. You can start with the official guides.

**Comment by eldadvcita** [comment]
Hi @casperisfine ,
I was under the impression that if I run the tests from within the gem folder, it will use shipit-engine's database.yaml.
