### ISSUE TITLE
Webhook delivery broken after #1151 with missing stack_id parameter for webhooks controller

### ISSUE THREAD

**Issue by airhorns** [Shopify/shipit-engine#1156]
I have been running the master version of shipit to debug an unrelated issue, and once upgrading past where #1151 was merged webhook delivery from Github started breaking for me in production:

```
Apr 12 04:13:19 PM  I, [2021-04-12T20:13:19.751405 #52]  INFO -- : [e77532d6-41ba-41f3-af7d-b39790fc6ec5] Completed 404 Not Found in 6ms (Allocations: 166)
Apr 12 04:13:19 PM  F, [2021-04-12T20:13:19.752516 #52] FATAL -- : [e77532d6-41ba-41f3-af7d-b39790fc6ec5]
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] ActiveRecord::RecordNotFound (Couldn't find Shipit::Stack without an ID):
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5]
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activerecord (6.1.3.1) lib/active_record/relation/finder_methods.rb:456:in `find_with_ids'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activerecord (6.1.3.1) lib/active_record/relation/finder_methods.rb:69:in `find'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activerecord (6.1.3.1) lib/active_record/querying.rb:22:in `find'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activerecord (6.1.3.1) lib/active_record/core.rb:325:in `find'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] shipit-engine (3c7172cfa1cc) app/controllers/shipit/webhooks_controller.rb:36:in `stack'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] shipit-engine (3c7172cfa1cc) app/controllers/shipit/webhooks_controller.rb:19:in `verify_signature'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/callbacks.rb:199:in `block in halting'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `block in invoke_before'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `each'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `invoke_before'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/callbacks.rb:105:in `run_callbacks'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activerecord (6.1.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/abstract_controller/base.rb:165:in `process'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionview (6.1.3.1) lib/action_view/rendering.rb:39:in `process'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_controller/metal.rb:190:in `dispatch'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_controller/metal.rb:254:in `dispatch'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] railties (6.1.3.1) lib/rails/railtie.rb:207:in `public_send'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] railties (6.1.3.1) lib/rails/railtie.rb:207:in `method_missing'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] sentry-rails (4.3.4) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/etag.rb:27:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/head.rb:12:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] railties (6.1.3.1) lib/rails/rack/logger.rb:37:in `call_app'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/method_override.rb:24:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/runtime.rb:22:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/static.rb:24:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] sentry-ruby-core (4.3.2) lib/sentry/rack/capture_exceptions.rb:23:in `block in call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] sentry-ruby-core (4.3.2) lib/sentry/hub.rb:52:in `with_scope'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] sentry-ruby-core (4.3.2) lib/sentry-ruby.rb:147:in `with_scope'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] sentry-ruby-core (4.3.2) lib/sentry/rack/capture_exceptions.rb:14:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] puma (3.12.6) lib/puma/configuration.rb:227:in `call'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] puma (3.12.6) lib/puma/server.rb:476:in `process_client'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] puma (3.12.6) lib/puma/server.rb:334:in `block in run'
Apr 12 04:13:19 PM  [e77532d6-41ba-41f3-af7d-b39790fc6ec5] puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

I believe it's because this 5 year old code https://github.com/Shopify/shipit-engine/blob/master/app/controllers/shipit/webhooks_controller.rb#L36 is being called now to retrieve the given stack for a webhook, which wasn't happening before. I took a quick look and couldn't find where that `stack_id` parameter is supposed to get set. Did the webooks#create route used to contain a `stack_id` parameter or something like that? The tests just set it explicitly also which is maybe why this snuck through: https://github.com/Shopify/shipit-engine/blob/master/test/controllers/webhooks_controller_test.rb#L186

**Comment by casperisfine** [comment]
Thanks for the report! Would you happen to know what GitHub event this hook maps to?

**Comment by airhorns** [comment]
AFAICT it was most/all of them, I wasn't see new commits or new commit statuses show up for any stacks.

**Comment by casperisfine** [comment]
Wait, looking at the code that can't possibly work. `params[:stack_id]` is a left over from the time when each Stack would install it's own webhook. Now we install a single hook per org.

I'm puzzled here.

**Comment by gigr** [comment]
We just rolled back https://github.com/Shopify/shipit-engine/pull/1151 in Shopify's internal Shipit instance because of this bug. I believe @Ginja is working on the fix, but it does mean that for now shipit-engine's master version is broken.

**Comment by Ginja** [comment]
@casperisfine you hit the nail on the head. `:stack_id` is no longer passed into any of the calls to the `WebhooksController`. I think we can rely on the fact that Github passes the organization info in the params to fix this. Testing it out now.
