### ISSUE TITLE
Phusion Passenger support

### ISSUE THREAD

**Issue by everestx** [Shopify/shipit-engine#519]
Is there any support to use phusion passenger to run shipit?  Seems to __not__ work out of the box, but I'm curious if your 1.) interested in support for it or 2.) I'm barking up the wrong tree.  My initial testing shows that passenger enterprise 4.x is not working.  I'm trying 5.x next, but thought it was worth an official response before I fiddle any further.

BTW: `rails s -p 3000` works like a champ. Many thanks!

**Comment by byroot** [comment]
> Is there any support to use phusion passenger to run shipit?

I didn't test it, but yes I expect users to be able to use any web server.

I haven't used passenger in years, but if Shipit is doing something incompatible with passenger, I'd be happy to fix it.

What do you mean by don't work exactly?

**Comment by everestx** [comment]
It appears that passenger doesn't grab hold of the stdout of the ruby process that starts up.  Either that or the process fails before passenger can get any output. That's the symptom, but I'm not sure of the cause.

passenger.log shows this:
```
[ 2016-01-28 08:26:41.0241 17727/7ff5316b7700 Pool2/Pool.h:1044 ]: Process (pid=18036, group=/pub/shipit/current#default) no longer exists! Detaching it from the pool.
App 18045 stdout:
App 17760 stderr: /opt/passenger-enterprise-server/lib/phusion_passenger/request_handler.rb:373:in `trap'
App 17760 stderr: :
App 17760 stderr: Invalid argument - SIGKILL
App 17760 stderr:  (
App 17760 stderr: Errno::EINVAL
App 17760 stderr: )
App 17760 stderr: 	from /opt/passenger-enterprise-server/lib/phusion_passenger/request_handler.rb:373:in `block in reset_signal_handlers'
App 17760 stderr: 	from /opt/passenger-enterprise-server/lib/phusion_passenger/request_handler.rb:371:in `each_key'
App 17760 stderr: 	from /opt/passenger-enterprise-server/lib/phusion_passenger/request_handler.rb:371:in `reset_signal_handlers'
App 17760 stderr: 	from /opt/passenger-enterprise-server/lib/phusion_passenger/request_handler.rb:195:in `main_loop'
App 17760 stderr: 	from /opt/passenger-enterprise-server/helper-scripts/rack-preloader.rb:139:in `<module:App>'
App 17760 stderr: 	from /opt/passenger-enterprise-server/helper-scripts/rack-preloader.rb:13:in `<module:PhusionPassenger>'
App 17760 stderr: 	from /opt/passenger-enterprise-server/helper-scripts/rack-preloader.rb:12:in `<main>'
```

**Comment by byroot** [comment]
```bash
$ passenger start
 --> Downloading a Phusion Passenger agent binary for your platform

 --> Installing Nginx 1.8.0 engine

--------------------------

 [passenger_native_support.bundle] trying to compile for the current Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Compilation succesful. The logs are here:
     /var/folders/xx/fpv0hjf95cscl2ys2rlp3f5r0000gn/T/passenger_native_support-18cc75r.log
 [passenger_native_support.bundle] successfully loaded.
=============== Phusion Passenger Standalone web server started ===============
PID file: /Users/byroot/workspace/shopify/shipit/tmp/pids/passenger.3000.pid
Log file: /Users/byroot/workspace/shopify/shipit/log/passenger.3000.log
Environment: development
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================


Started HEAD "/" for 127.0.0.1 at 2016-01-28 09:19:57 -0500
  ActiveRecord::SchemaMigration Load (11.9ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by Shipit::StacksController#index as HTML
Redirected to http://0.0.0.0/github/auth/github?origin=http%3A%2F%2F0.0.0.0%2F
Filter chain halted as :force_github_authentication rendered or redirected
Completed 302 Found in 34ms (ActiveRecord: 0.0ms)


Started GET "/" for 127.0.0.1 at 2016-01-28 09:20:15 -0500
Processing by Shipit::StacksController#index as HTML
  Shipit::User Load (23.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
   (1.5ms)  SELECT DISTINCT `commits`.`stack_id` FROM `commits` WHERE (author_id = 1 or committer_id = 1)
  Shipit::Stack Load (0.5ms)  SELECT `stacks`.* FROM `stacks`  ORDER BY (undeployed_commits_count > 0) desc, `stacks`.`tasks_count` DESC
  Rendered /Users/byroot/.rvm/gems/ruby-2.1.5/bundler/gems/shipit-engine-8007264631ba/app/views/shipit/stacks/index.html.erb within layouts/shipit (5.1ms)
Completed 200 OK in 661ms (Views: 469.6ms | ActiveRecord: 110.9ms)
^CStopping web server... done
$ passenger -v
Phusion Passenger 5.0.23

```

I just tried 5.0, worked fine.

**Comment by everestx** [comment]
Yeah, I tried 5.0.23 (on passenger enterprise) with apache 2.4 and it worked fine too.  Awesome!

**Comment by byroot** [comment]
Great!
