### ISSUE TITLE
Commands timing out can sometimes leave tasks in running state

### ISSUE THREAD

**Issue by byroot** [Shopify/shipit-engine#520]
That exception is supposed to be rescued and the task marked as errored

```ruby
Errno::EIO: Input/output error @ io_getpartial - /dev/pts/0
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:117:in `readpartial'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:117:in `block (2 levels) in read_stream'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:126:in `with_timeout'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:116:in `block in read_stream'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:115:in `loop'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:115:in `read_stream'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:147:in `block in kill_and_wait'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:35:in `catch'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:146:in `kill_and_wait'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:130:in `terminate!'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:89:in `rescue in stream'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:84:in `stream'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/lib/shipit/command.rb:109:in `stream!'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/app/jobs/shipit/perform_task_job.rb:51:in `capture'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/app/jobs/shipit/perform_task_job.rb:44:in `block in capture_all'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/app/jobs/shipit/perform_task_job.rb:44:in `map'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/app/jobs/shipit/perform_task_job.rb:44:in `capture_all'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/app/jobs/shipit/perform_task_job.rb:31:in `block in perform_task'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:245:in `block in with_clean_env'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:232:in `with_original_env'
  /usr/lib/shopify-ruby/2.1.6-shopify2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:238:in `with_clean_env'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/app/jobs/shipit/perform_task_job.rb:29:in `perform_task'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/app/jobs/shipit/perform_task_job.rb:20:in `run'
  /app/config/initializers/statsd.rb:11:in `run'
  /artifacts/ruby/2.1.0/bundler/gems/shipit-engine-8007264631ba/app/jobs/shipit/perform_task_job.rb:12:in `perform'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:32:in `block in perform_now'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
  /artifacts/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/active_job.rb:46:in `call'
  /artifacts/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/active_job.rb:46:in `perform'
  /artifacts/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `instance_exec'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `block in simple'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `block in around'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
  /artifacts/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `instance_exec'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `block in simple'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `block in around'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:23:in `call'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:43:in `block in tag_logger'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `tagged'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:43:in `tag_logger'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `instance_exec'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `block in simple'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `block in around'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
  /artifacts/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:31:in `perform_now'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:21:in `execute'
  /artifacts/ruby/2.1.0/gems/activejob-4.2.5.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
  /artifacts/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
  /artifacts/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
  /artifacts/ruby/2.1.0/gems/newrelic_rpm-3.14.0.305/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
  /artifacts/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

I'll take a closer look at it soon.

cc @gmalette @djoume

**Comment by sgringwe** [comment]
I'm also running into this error and leaving the app in a weird state. I'm also not sure how to fix this, yet.

**Comment by byroot** [comment]
@sgringwe The workaround described here: https://github.com/Shopify/shipit-engine/issues/562#issuecomment-204561300 should help until I fix the root cause.
