### ISSUE TITLE
Example review checklist produces syntax error

### ISSUE THREAD

**Issue by teu** [Shopify/shipit-engine#534]
Ran the example:

```
deploy:
  variables:
    -
      name: FORCE_REBUILD
      title: Force artifacts rebuild
      default: '0'
review:
  monitoring:
    - iframe: https://example.com
review:
  checklist:
    - >
    Do you know if it is safe to revert the code being shipped? What happens if we need to undo this deploy?
    - Has the Docs team been notified of any major changes to the app?
    - Is the app stable right now?
```

produces:
```
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 13 column 5
	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:143:in `parse'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:143:in `load'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/app/models/shipit/deploy_spec/file_system.rb:56:in `read_config'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/app/models/shipit/deploy_spec/file_system.rb:52:in `load_config'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/app/models/shipit/deploy_spec/file_system.rb:47:in `config'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/app/models/shipit/deploy_spec.rb:53:in `dependencies_steps'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/lib/shipit/task_commands.rb:15:in `install_dependencies'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/app/jobs/shipit/perform_task_job.rb:30:in `block in perform_task'	/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler.rb:219:in `block in with_clean_env'	/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler.rb:199:in `with_original_env'	/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.11.2/lib/bundler.rb:205:in `with_clean_env'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/app/jobs/shipit/perform_task_job.rb:29:in `perform_task'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/app/jobs/shipit/perform_task_job.rb:20:in `run'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/bundler/gems/shipit-engine-8b51fed7f4e9/app/jobs/shipit/perform_task_job.rb:12:in `perform'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:32:in `block in perform_now'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `instance_exec'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `block in simple'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `block in around'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:23:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:43:in `block in tag_logger'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:26:in `tagged'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `tagged'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:43:in `tag_logger'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `instance_exec'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:342:in `block in simple'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:497:in `block in around'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:31:in `perform_now'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/execution.rb:21:in `execute'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/activejob-4.2.5.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:150:in `execute_job'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/logging.rb:30:in `with_context'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `call'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:127:in `block in process'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:166:in `stats'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:126:in `process'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:79:in `process_one'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/processor.rb:67:in `run'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:16:in `watchdog'	/var/capistrano/shipit/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Also unsure where the iframe is supposed to be?

**Comment by byroot** [comment]
Good catch. Fixed in d2020b438615bc9b09fba28d32ecc80d7193025c

Also you have 2 `review` keys, you have to merge them:

```yaml
deploy:
  variables:
    -
      name: FORCE_REBUILD
      title: Force artifacts rebuild
      default: '0'
review:
  monitoring:
    - iframe: https://example.com
  checklist:
    - >
      Do you know if it is safe to revert the code being shipped? What happens if we need to undo this deploy?
    - Has the Docs team been notified of any major changes to the app?
    - Is the app stable right now?
```

> Also unsure where the iframe is supposed to be?

It's to include monitoring graphs etc on the review page. e.g. a new relic graph or something like that.

**Comment by teu** [comment]
Which page is the review page? Does this require a checklist to work?

**Comment by byroot** [comment]
> Which page is the review page?

When you click on "Deploy", it doesn't trigger the deploy immediately. It just send you to the "Review" page where you can confirm.

![capture d ecran 2016-02-19 a 13 31 36](https://cloud.githubusercontent.com/assets/44640/13185037/212da40a-d70d-11e5-9b79-83dbf3bb5014.png)

>  Does this require a checklist to work?

The checklist is not mandatory.

**Comment by teu** [comment]
Weird, iframe is showing but only an empty doc, domain is https://app.uxpin.com
