### ISSUE TITLE
Shipit crash if github commit message contains an emoji

### ISSUE THREAD

**Issue by pollosp** [Shopify/shipit-engine#597]
If your message commit in github has an utf8mb4 emoji shipit sidekiq worker crash with an error like this:
```
2016-08-08T15:39:47.036Z 30418 TID-oxr5o1alk WARN: ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xF0\x9F\xA4\x96' for column 'message' at row 1: INSERT INTO `commits` (`stack_id`, `sha`, `message`, `author_id`, `committer_id`, `committed_at`, `authored_at`, `created_at`, `updated_at`) VALUES (2, '64c6a0df11d4ecb7348a8d94667028be666653', 'INFRAXXX (#4519)\n\n* commit1\r\n\r\n* commit2<U+1F916>', 13, 1, '2016-08-08 09:38:35', '2016-08-08 09:38:35', '2016-08-08 15:39:47', '2016-08-08 15:39:47')
```
`<U+1F916>` is character  🤖 .

We have 'fixed' this behavior modifying the model related with the commit `app/model/commit.rb` and replacing `message: commit.commit.message,` with `message: commit.commit.message.each_char.select{|c| c.bytes.count < 4 }.join(''),`  which clean utf8mb4 characters.

There is more information about this issue here:
http://blog.arkency.com/2015/05/how-to-store-emoji-in-a-rails-app-with-a-mysql-database/

Thanks :)

**Comment by gmalette** [comment]
The host application is responsible for the database config, so you can configure your `database.yml` before creating the tables. 

```yml
default: &default
  ...
  collation: utf8mb4_bin
```

I agree that Shipit should enforce that however.

**Comment by pollosp** [comment]
@gmalette it was our first approach and totally agree that shipit should take this into account to make this software even better than now :). 

We have added encoding and migration into the YML and ran a `db:migrate` and even we ran `db:drop` and `db:migrate` 
But we are running it on mysql 5.5 and unfortunately it didn't work because the indexes were only 767 bytes long by default, we try to make indexes smaller with something like `ALTER TABLE `mytable` ADD UNIQUE ( column1(15), column2(200) );` but it didn't work as we expected so it is why we have decided to remove utfmb4 characters directly in the model.

**Comment by gmalette** [comment]
Gotcha! That's why we'll need to make sure Shipit handles it. Thanks :)

**Comment by casperisfine** [comment]
We run shipit with uft8m4 at Shopify, so all indexed columns are sized properly so that it works. 

Now maybe because some columns are reduced in later migrations it might not work if you run `db:migrate` from scratch. I'll check that out.

**Comment by casperisfine** [comment]
Also 👋 @orenmazor

**Comment by casperisfine** [comment]
Ok, so I just did a fresh install to be sure and I ran `bin/rake db:create db:migrate`.

The resulting tables are `utf8mb4`:

```sql
mysql> show create table commits\G
*************************** 1. row ***************************
       Table: commits
Create Table: CREATE TABLE `commits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stack_id` int(11) NOT NULL,
  `author_id` int(11) NOT NULL,
  `committer_id` int(11) NOT NULL,
  `sha` varchar(40) COLLATE utf8mb4_bin NOT NULL,
  `message` text COLLATE utf8mb4_bin NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `detached` tinyint(1) NOT NULL DEFAULT '0',
  `authored_at` datetime NOT NULL,
  `committed_at` datetime NOT NULL,
  `additions` int(11) DEFAULT NULL,
  `deletions` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_commits_on_author_id` (`author_id`) USING BTREE,
  KEY `index_commits_on_committer_id` (`committer_id`) USING BTREE,
  KEY `index_commits_on_created_at` (`created_at`) USING BTREE,
  KEY `index_commits_on_stack_id` (`stack_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

I'm using MySQL 5.7 but the index size limit is still 767 bytes so that must not be it.

@pollosp if you can provide reproduction step for a new project form scratch that would be very helpful.

Also if it can help you, here's the migration I used about a year ago to fix our database when I figured we forgot to define tables as utf8mb4:

```ruby
class MigrateAllTablesToUtf8Mb4 < ActiveRecord::Migration
  def up
    database = ActiveRecord::Base.connection.quote_table_name(ActiveRecord::Base.connection.current_database)
    exec "ALTER DATABASE #{database} DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"

    execute("SHOW TABLES").each do |(name)|
      next if name == 'schema_migrations'
      convert_table(name)
    end
  end

  def convert_table(name)
    exec "ALTER TABLE #{name} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
  end

  def down
  end

  def exec(query)
    say query
    execute query
  end
end
```

And finally I think what we could do is to customize the `database.yml` from the `template.rb` to warn about this. Also a section in the readme wouldn't harm.

**Comment by josacar** [comment]
Running `rake db:drop db:create db:migrate`:

```
-- add_index("github_hooks", ["organization", "event"], {:name=>"index_github_hooks_on_organization_and_event", :unique=>true, :using=>:btree})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_github_hooks_on_organization_and_event` USING btree ON `github_hooks` (`organization`, `event`) /home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:535:in `add_index'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:665:in `block in method_missing'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:634:in `block in say_with_time'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:634:in `say_with_time'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:654:in `method_missing'
/home/vagrant/code/platform/apps/shipit/db/migrate/20150717193930_create_baseline.shipit_engine.rb:62:in `change'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:608:in `exec_migration'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:591:in `block in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:590:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:959:in `block in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_github_hooks_on_organization_and_event` USING btree ON `github_hooks` (`organization`, `event`)
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:535:in `add_index'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:665:in `block in method_missing'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:634:in `block in say_with_time'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:634:in `say_with_time'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:654:in `method_missing'
/home/vagrant/code/platform/apps/shipit/db/migrate/20150717193930_create_baseline.shipit_engine.rb:62:in `change'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:608:in `exec_migration'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:591:in `block in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:590:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:959:in `block in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Mysql2::Error: Specified key was too long; max key length is 767 bytes
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:535:in `add_index'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:665:in `block in method_missing'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:634:in `block in say_with_time'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:634:in `say_with_time'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:654:in `method_missing'
/home/vagrant/code/platform/apps/shipit/db/migrate/20150717193930_create_baseline.shipit_engine.rb:62:in `change'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:608:in `exec_migration'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:591:in `block in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:590:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:959:in `block in migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by casperisfine** [comment]
Weird. It fails during the `create_baseline`, which is logic in a way. I'll try to repro again.

In the meantime, what version /revision of the gem are you running?

**Comment by josacar** [comment]
shipit-engine (0.11.0) and MySQL 5.5

**Comment by casperisfine** [comment]
Ok my bad. The MySQL documentation was misleading:
  - First it claims the limit is still 767 bytes for 5.7: http://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html
  - But if you keep looking, you see that `5.7.7` enabled `innodb_large_prefix` by default: http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix

So what I'll do here, is that I'll edit the baseline migration to be compatible with that restriction, I just need to install an older MySQL to be able to test properly. Once I'm done you will be able to replace the migration and reset your DB.

Another alternative for you is to reconfigure your MySQL instance to support large prefix.

**Comment by josacar** [comment]
Doesn't work for me.

One suggestion, what about keeping index small instead cropping column size?

This is what I mean:

https://github.com/Shopify/shipit-engine/compare/master...peertransfer:reduce-size-indexes

**Comment by casperisfine** [comment]
Hum. I must have forgotten some fields. What you suggest is indeed a possibility, but a while ago I already cropped column size, so might as well stay consistent.

**Comment by casperisfine** [comment]
Ok so I did totally forget one of the migrations. I just pushed on master: https://github.com/Shopify/shipit-engine/commit/820716d2fc6640e366f0153fb8df78ba167c175b

This time I installed MySQL 5.5 to test, it works just fine (I was lazy before sorry :/)

**Comment by josacar** [comment]
Great. Working fine.

Thanks a lot!

**Comment by pollosp** [comment]
Thanks guys :)
