### ISSUE TITLE
Not detecting git release versions

### ISSUE THREAD

**Issue by josacar** [Shopify/shipit-engine#599]
With a no git release like `2.8.0.rc3` shipit crashes:

```
$ git --version
git version 2.8.0.rc3
```

```
irb(main):001:0> Shipit::Commands.git_version
ArgumentError: Malformed version number string 2.8.0.
        from /usr/local/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/version.rb:206:in `initialize'
        from /usr/local/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/version.rb:198:in `new'
        from /usr/local/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/version.rb:198:in `new'
        from /home/vagrant/bundler/2.2.2/ruby/2.2.0/bundler/gems/shipit-engine-820716d2fc66/lib/shipit/commands.rb:11:in `git_version'
        from (irb):1
        from /home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/console.rb:110:in `start'
        from /home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/console.rb:9:in `start'
        from /home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/vagrant/bundler/2.2.2/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by casperisfine** [comment]
Shouldn't be hard to fix. Hold on.

**Comment by josacar** [comment]
Maybe this could solve it ``` `git --version` =~ /(\d+\.\d+\.\d+)/```

**Comment by casperisfine** [comment]
That is what I'm currently committing :)

**Comment by casperisfine** [comment]
I just pushed the fix.

**Comment by josacar** [comment]
Thanks a lot 🍻
